apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-gitops-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/vllm
    repoURL: https://github.com/luis5tb/gitops-demos.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true